version: '3.9'
services:
  nginx_frontend:
    image: nginx:latest
    container_name: nginx-front
    networks:
      cours_net:
        ipv4_address: 172.28.0.2


  nginx_backend:
    image: nginx:latest
    container_name: nginx-back
    networks:
      cours_net:
        ipv4_address: 172.28.0.3
    ports:
      - "8080:80"
    volumes:
      - ./code:/code
      - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  
  php-fpm:
    image: php:7-fpm
    container_name: php-fpm
    networks:
      cours_net:
        ipv4_address: 172.28.0.4
    volumes:
    - ./code:/code
