version: '3.9'
services:
  nginx_frontend:
    image: nginx
    container_name: nginx-front
    networks:
      cours_net:
        ipv4_address: 172.28.0.2
    ports:
      - "80:80"
    volumes:
      - ./code/nginx.conf:/etc/nginx/nginx.conf:rw
    links:
      - nginx_backend
      - icinga2

  nginx_backend:
    image: nginx
    container_name: nginx-back
    networks:
      cours_net:
        ipv4_address: 172.28.0.3
    ports:
      - "8080:80"
    volumes:
      - ./site:/code
      - ./site/site.conf:/etc/nginx/conf.d/default.conf:rw
    links:
      - php-fpm
  
  php-fpm:
    image: php:7-fpm
    container_name: php-fpm
    networks:
      cours_net:
        ipv4_address: 172.28.0.4
    volumes:
      - ./site:/code

networks:
  cours_net:
    external: true
    name: cours-network
